apiVersion: v1
kind: Pod
metadata:
  name: pd1
spec:
  containers:
  -  name: c1
     image: jayaramarao/stress
     command: ["sleep","300"]
     resources:
       limits:
         memory: "128Mi"
         cpu: "500m"
       requests:
         memory: "64Mi"
         cpu: "250m"
