apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
spec:
  containers:
  - name: stress
    image: jayaramarao/stress
    command: ["sleep","200"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limitis:
        memory: "128Mi"
        cpu: "500m"
      
